### ISSUE TITLE
[Incident] Dask Gateway gives `500` errors in the OpenScapes hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1116]
# Summary

The OpenScapes community has reported that their Dask Gateway setup is not working. The following code:

```python
from dask_gateway import Gateway, GatewayCluster

gateway = Gateway()
options = gateway.cluster_options()
cluster = GatewayCluster(cluster_options=options)
```

yields the following error:

<details>
<summary>Error here</summary>

```python
GatewayServerError                        Traceback (most recent call last)
Input In [1], in <cell line: 5>()
      3 gateway = Gateway()
      4 options = gateway.cluster_options()
----> 5 cluster = GatewayCluster(cluster_options=options)

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:814, in GatewayCluster.__init__(self, address, proxy_address, public_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    802 def __init__(
    803     self,
    804     address=None,
   (...)
    812     **kwargs,
    813 ):
--> 814     self._init_internal(
    815         address=address,
    816         proxy_address=proxy_address,
    817         public_address=public_address,
    818         auth=auth,
    819         cluster_options=cluster_options,
    820         cluster_kwargs=kwargs,
    821         shutdown_on_close=shutdown_on_close,
    822         asynchronous=asynchronous,
    823         loop=loop,
    824     )

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:919, in GatewayCluster._init_internal(self, address, proxy_address, public_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    917     self.status = "starting"
    918 if not self.asynchronous:
--> 919     self.gateway.sync(self._start_internal)

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:343, in Gateway.sync(self, func, *args, **kwargs)
    339 future = asyncio.run_coroutine_threadsafe(
    340     func(*args, **kwargs), self.loop.asyncio_loop
    341 )
    342 try:
--> 343     return future.result()
    344 except BaseException:
    345     future.cancel()

File /srv/conda/envs/notebook/lib/python3.9/concurrent/futures/_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File /srv/conda/envs/notebook/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:933, in GatewayCluster._start_internal(self)
    931     self._start_task = asyncio.ensure_future(self._start_async())
    932 try:
--> 933     await self._start_task
    934 except BaseException:
    935     # On exception, cleanup
    936     await self._stop_internal()

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:946, in GatewayCluster._start_async(self)
    944 if self.status == "created":
    945     self.status = "starting"
--> 946     self.name = await self.gateway._submit(
    947         cluster_options=self._cluster_options, **self._cluster_kwargs
    948     )
    949 # Connect to cluster
    950 try:

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:535, in Gateway._submit(self, cluster_options, **kwargs)
    533     options = self._config_cluster_options()
    534     options.update(kwargs)
--> 535 resp = await self._request("POST", url, json={"cluster_options": options})
    536 data = await resp.json()
    537 return data["name"]

File /srv/conda/envs/notebook/lib/python3.9/site-packages/dask_gateway/client.py:417, in Gateway._request(self, method, url, json)
    415     raise GatewayClusterError(msg)
    416 elif resp.status == 500:
--> 417     raise GatewayServerError(msg)
    418 else:
    419     resp.raise_for_status()

GatewayServerError: 500 Internal Server Error

Server got itself in trouble
```

</details>

## Extra context

- Hub URL: openscapes.2i2c.cloud
- Their Dask Gateway configuration:

   https://github.com/2i2c-org/infrastructure/blob/87ee7de3de3903e62e8f196b1dad63aab0c8fb8a/config/clusters/openscapes/common.values.yaml#L121-L125
- Noting that this is different from the Pangeo Hubs dask gateway configuration:

   https://github.com/2i2c-org/infrastructure/blob/87ee7de3de3903e62e8f196b1dad63aab0c8fb8a/config/clusters/pangeo-hubs/common.values.yaml#L119-L128
- **User environment**: They are using a Pangeo-based image (`FROM pangeo/base-image:2021.09.30`). [Environment repo is here](https://github.com/NASA-Openscapes/corn).

**Comment by consideRatio** [comment]
This seems reasonable to debug by inspecting logs of the pod named something with `api` (dask-gateway-server software is running there).

**Comment by yuvipanda** [comment]
Copying my message on freshdesk:

Am looking at it now, and see the following errors in the logs:

```
[E 2022-03-16 03:15:04.509 DaskGateway] Error in cluster informer, retrying...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 161, in run
    initial = await method(**self.method_kwargs)
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 180, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 192, in GET
    return (await self.request("GET", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 186, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.exceptions.ApiException: (401)
Reason: Unauthorized
```
I restarted the dask-gateway controller pod, and it seems to have fixed the issue. I can run the code you provided and it doesn't error out. Can you try it out and let me know?

**Comment by consideRatio** [comment]
We think of this as solved, but it isn't confirmed.

**Comment by choldgraf** [comment]
Quick thought here: FreshDesk has two different "resolution" states for tickets:

- `resolved`: means that **we think** we have resolved the issue. We take an action, think it's resolved, send an email to the other person to confirm, and then mark the ticket as "resolved"
- `closed`: means that **they have confirmed** that the issue is resolved, or that they didn't respond when we pinged them. But they also have the option of saying "no this is still broken" in which case we move back to "open".

In this case, it feels like the ticket should be marked `resolved`, and we should close this issue when the ticket is marked `closed` (either via their confirmation, or no response after ~48 working hours). I think we could follow this practice more generally for support ticket -> github issue workflows.

Does that make sense?

**Comment by damianavila** [comment]
It makes sense to me, @choldgraf. 

Btw, we have confirmation about the issues being fixed here: https://github.com/2i2c-org/infrastructure/issues/1076#issuecomment-1069808122

So, I will mark the support ticket as closed and also close this issue now!
