### ISSUE TITLE
Investigate a dask-gateway cluster's scheduler startup and node allocation

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#1257]
@rabernat opened a support ticket about a 404 response in the LEAP hub, see https://2i2c.freshdesk.com/a/tickets/126.

Our configuration mentions putting the dask-cluster schedulers created by our dask-gateway on the user nodes, but in practice just applies a toleration for the user noes, but then declares a nodeSelector with a label: `k8s.dask.org/node-purpose: scheduler`. Due to that, I suspect something is problematic here.

1. Perhaps the scheduler pod will fail to start because there is no k8s node with such label?
2. Perhaps the scheduler pod starts, but on a different node than the user nodes, which makes it slow to start and makes our note incorrect.

https://github.com/2i2c-org/infrastructure/blob/45e51afe8335e9f8efc700e3a95f3c21dd2bf36a/helm-charts/daskhub/values.yaml#L109-L125

Note that I referenced the general configuration above, but @rabernat's issue is in the LEAP hub, so investigations if something is different specifically for that hub is also relevant to look into.

### Update 1 - our config sets the relevant node-label

The LEAP cluster is a GCP cluster, and it seems that nodes should be provisioned with the label of relevance.

https://github.com/2i2c-org/infrastructure/blob/45e51afe8335e9f8efc700e3a95f3c21dd2bf36a/terraform/gcp/cluster.tf#L237-L241

### Update 2 - the node gets the relevant node-label

```yaml
  # ...
  labels:
    # ...
    hub.jupyter.org/node-purpose: user
    k8s.dask.org/node-purpose: scheduler
```

**Comment by consideRatio** [comment]
@GeorgianaElena observed that we had the following errors show up in the dask-gateway controller pod, responsible for reacting to changes to DaskCluster resources.

```python-traceback
[E 2022-04-28 18:18:36.828 KubeController] Error in pod informer, retrying...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 183, in run
    async for ev in watch(method, **kwargs):
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 71, in watch
    resp = await method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 59, in func
    return await method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 180, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 192, in GET
    return (await self.request("GET", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 176, in request
    r = await self.pool_manager.request(**args)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 551, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 605, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

This error was regularly showing up but with successful notes in between such as...

```
[I 2022-04-29 08:15:38.015 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:15:38.200 KubeController] Creating new credentials for cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:15:38.227 KubeController] Creating scheduler pod for cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:15:38.282 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:15:38.283 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:15:38.283 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:13.023 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:13.023 KubeController] Creating scheduler service for cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:13.081 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:13.081 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:13.082 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.344 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.344 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.384 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.384 KubeController] Creating scheduler HTTP route for cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.406 KubeController] Creating scheduler TCP route for cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.426 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.427 KubeController] Reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
[I 2022-04-29 08:18:20.427 KubeController] Finished reconciling cluster prod.15b75e4b71134ff2a3fe222f55e05b2a
```

---

Besides this there was also once instance of this...

```
[W 2022-04-28 13:38:10.622 KubeController] Failed to create pod in namespace prod - Operation cannot be fulfilled on resourcequotas "gke-resource-quotas": the object has been modified; please apply your changes to the latest version and try again
```

---

Overall, I'm not sure what caused the issue @rabernat observed. Practially I suggest we upgrade to dask-gateway helm chart 2022.4.0 before any further investigative work is done into this as its seems intermittent.

I'll close this as resolved for now and have opened https://github.com/2i2c-org/infrastructure/issues/1259 to track work with regards to upgrading to 2022.4.0.
