### ISSUE TITLE
"ModuleNotFoundError: No module named 'markdownTable'" when running deployer locally

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1559]
I tried installing things from `requirements.txt` but that didn't help either.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/yuvipanda/code/similar-hubs/deployer/__main__.py", line 4, in <module>
    import cli
  File "/Users/yuvipanda/code/similar-hubs/deployer/cli.py", line 6, in <module>
    from config_validation import (
  File "/Users/yuvipanda/code/similar-hubs/deployer/config_validation.py", line 13, in <module>
    from cluster import Cluster
  File "/Users/yuvipanda/code/similar-hubs/deployer/cluster.py", line 9, in <module>
    from hub import Hub
  File "/Users/yuvipanda/code/similar-hubs/deployer/hub.py", line 12, in <module>
    from utils import print_colour
  File "/Users/yuvipanda/code/similar-hubs/deployer/utils.py", line 4, in <module>
    from markdownTable import markdownTable
ModuleNotFoundError: No module named 'markdownTable'
```

**Comment by sgibson91** [comment]
I will look into this, but... This code shouldn't be running locally anyway. Pretty certain I put it behind a `if CI is True` flag, where `CI` is an environment variable set by the GitHub Actions runner.

**Comment by sgibson91** [comment]
Also, what version of Python are you using? I just create a fresh env with 3.10 and it worked fine

```
conda create -n test python=3.10
conda activate test
pip install py-markdown-table
python
>>> from markdownTable import markdownTable
>>> quit()
pip freeze | grep "py-markdown-table"  # Returned version 0.2.2, so I will pin that in requirements.txt
```

**Comment by yuvipanda** [comment]
@sgibson91 yeah, I commented out the import and everything works fine. The code is definitely not used locally, but the module is imported locally.

I'm on python 3.10, and here's list of packages:

```
Package                       Version
----------------------------- -----------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anyio                         3.6.1
appnope                       0.1.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.5
async-timeout                 4.0.2
attrs                         21.4.0
auth0-python                  3.23.1
Babel                         2.10.3
backcall                      0.2.0
beautifulsoup4                4.11.1
black                         22.6.0
bleach                        5.0.1
certifi                       2022.6.15
cffi                          1.15.0
charset-normalizer            2.0.12
chartpress                    1.3.0
click                         8.1.3
colorama                      0.4.5
commonmark                    0.9.1
cryptography                  37.0.2
debugpy                       1.6.2
decorator                     5.1.1
defusedxml                    0.7.1
docker                        5.0.3
docutils                      0.17.1
entrypoints                   0.4
executing                     0.8.3
fastjsonschema                2.15.3
frozenlist                    1.3.0
idna                          3.3
imagesize                     1.4.1
iniconfig                     1.1.1
ipykernel                     6.15.1
ipython                       8.4.0
ipython-genutils              0.2.0
jedi                          0.18.1
jhub-client                   0.1.6
Jinja2                        3.1.2
json5                         0.9.8
jsonschema                    4.7.2
jupyter-client                7.3.4
jupyter-core                  4.11.1
jupyter-server                1.18.1
jupyterlab                    3.4.3
jupyterlab-pygments           0.2.2
jupyterlab-server             2.15.0
linkify-it-py                 1.0.3
livereload                    2.6.3
markdown-it-py                2.1.0
MarkupSafe                    2.1.1
matplotlib-inline             0.1.3
mdit-py-plugins               0.3.0
mdurl                         0.1.1
mistune                       0.8.4
multidict                     6.0.2
mypy-extensions               0.4.3
myst-parser                   0.18.0
nbclassic                     0.4.2
nbclient                      0.6.6
nbconvert                     6.5.0
nbformat                      5.4.0
nest-asyncio                  1.5.5
notebook-shim                 0.1.0
numpy                         1.23.0
packaging                     21.3
pandas                        1.4.3
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.9.0
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.0.4
platformdirs                  2.5.2
pluggy                        1.0.0
prometheus-client             0.14.1
prompt-toolkit                3.0.30
psutil                        5.9.1
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
py-markdown-table             0.2.2
pycparser                     2.21
pydata-sphinx-theme           0.8.1
Pygments                      2.12.0
PyJWT                         2.4.0
pyparsing                     3.0.9
pyrsistent                    0.18.1
pytest                        7.1.2
pytest-asyncio                0.19.0
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         23.2.0
requests                      2.28.0
rich                          12.5.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
scipy                         1.8.1
Send2Trash                    1.8.0
setuptools                    60.10.0
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        4.5.0
sphinx-2i2c-theme             0.0.1
sphinx-autobuild              2021.3.14
sphinx-book-theme             0.3.2
sphinx-copybutton             0.5.0
sphinx-panels                 0.6.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.3.0
terminado                     0.15.0
tinycss2                      1.1.1
tomli                         2.0.1
tornado                       6.2
traitlets                     5.3.0
typing_extensions             4.3.0
uc-micro-py                   1.0.1
urllib3                       1.26.9
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.3.3
yarl                          1.7.2

```

**Comment by sgibson91** [comment]
I fear this may be a deep package mismatch somewhere as I am not able to reproduce this locally 😔 I will share my list of packages when I'm back at my laptop

**Comment by sgibson91** [comment]
Here's my list of packages:

```
Package            Version
------------------ ---------
aiohttp            3.8.1
aiosignal          1.2.0
appnope            0.1.2
asttokens          2.0.5
async-timeout      4.0.2
attrs              21.4.0
auth0-python       3.23.1
backcall           0.2.0
certifi            2022.6.15
cffi               1.15.1
charset-normalizer 2.1.0
chartpress         1.3.0
commonmark         0.9.1
cryptography       37.0.4
debugpy            1.5.1
decorator          5.1.1
docker             5.0.3
entrypoints        0.4
executing          0.8.3
frozenlist         1.3.0
idna               3.3
iniconfig          1.1.1
ipykernel          6.9.1
ipython            8.4.0
jedi               0.18.1
jhub-client        0.1.6
jsonschema         4.7.2
jupyter-client     7.2.2
jupyter-core       4.10.0
matplotlib-inline  0.1.2
multidict          6.0.2
nest-asyncio       1.5.5
packaging          21.3
parso              0.8.3
pexpect            4.8.0
pickleshare        0.7.5
pip                22.1.2
pluggy             1.0.0
prompt-toolkit     3.0.20
ptyprocess         0.7.0
pure-eval          0.2.2
py                 1.11.0
py-markdown-table  0.2.2
pycparser          2.21
Pygments           2.11.2
PyJWT              2.4.0
pyparsing          3.0.9
pyrsistent         0.18.1
pytest             7.1.2
pytest-asyncio     0.19.0
python-dateutil    2.8.2
pyzmq              23.2.0
requests           2.28.1
rich               12.5.1
ruamel.yaml        0.17.21
ruamel.yaml.clib   0.2.6
setuptools         61.2.0
six                1.16.0
stack-data         0.2.0
tomli              2.0.1
tornado            6.1
traitlets          5.1.1
urllib3            1.26.10
wcwidth            0.2.5
websocket-client   1.3.3
wheel              0.37.1
yarl               1.7.2
```

**Comment by sgibson91** [comment]
This is the diff of our two lists using the command `diff --ignore-all-space --suppress-common-lines --side-by-side yuvi-list.py sarah-list.py`: (Lord knows why I saved them as .py files instead of .txt?)

```
alabaster                     0.7.12			      |	appnope            0.1.2
anyio                         3.6.1			      <
appnope                       0.1.3			      <
argon2-cffi                   21.3.0			      <
argon2-cffi-bindings          21.2.0			      <
Babel                         2.10.3			      <
beautifulsoup4                4.11.1			      <
black                         22.6.0			      <
bleach                        5.0.1			      <
cffi                          1.15.0			      |	cffi               1.15.1
charset-normalizer            2.0.12			      |	charset-normalizer 2.1.0
click                         8.1.3			      <
colorama                      0.4.5			      <
cryptography                  37.0.2			      |	cryptography       37.0.4
debugpy                       1.6.2			      |	debugpy            1.5.1
defusedxml                    0.7.1			      <
docutils                      0.17.1			      <
fastjsonschema                2.15.3			      <
imagesize                     1.4.1			      <
ipykernel                     6.15.1			      |	ipykernel          6.9.1
ipython-genutils              0.2.0			      <
Jinja2                        3.1.2			      <
json5                         0.9.8			      <
jupyter-client                7.3.4			      |	jupyter-client     7.2.2
jupyter-core                  4.11.1			      |	jupyter-core       4.10.0
jupyter-server                1.18.1			      |	matplotlib-inline  0.1.2
jupyterlab                    3.4.3			      <
jupyterlab-pygments           0.2.2			      <
jupyterlab-server             2.15.0			      <
linkify-it-py                 1.0.3			      <
livereload                    2.6.3			      <
markdown-it-py                2.1.0			      <
MarkupSafe                    2.1.1			      <
matplotlib-inline             0.1.3			      <
mdit-py-plugins               0.3.0			      <
mdurl                         0.1.1			      <
mistune                       0.8.4			      <
mypy-extensions               0.4.3			      <
myst-parser                   0.18.0			      <
nbclassic                     0.4.2			      <
nbclient                      0.6.6			      <
nbconvert                     6.5.0			      <
nbformat                      5.4.0			      <
notebook-shim                 0.1.0			      <
numpy                         1.23.0			      <
pandas                        1.4.3			      <
pandocfilters                 1.5.0			      <
pathspec                      0.9.0			      <
pip                           22.0.4			      |	pip                22.1.2
platformdirs                  2.5.2			      <
prometheus-client             0.14.1			      |	prompt-toolkit     3.0.20
prompt-toolkit                3.0.30			      <
psutil                        5.9.1			      <
pydata-sphinx-theme           0.8.1			      |	Pygments           2.11.2
Pygments                      2.12.0			      <
pytz                          2022.1			      <
PyYAML                        6.0			      <
requests                      2.28.0			      |	requests           2.28.1
scipy                         1.8.1			      |	setuptools         61.2.0
Send2Trash                    1.8.0			      <
setuptools                    60.10.0			      <
sniffio                       1.2.0			      |	stack-data         0.2.0
snowballstemmer               2.2.0			      <
soupsieve                     2.3.2.post1		      <
Sphinx                        4.5.0			      <
sphinx-2i2c-theme             0.0.1			      <
sphinx-autobuild              2021.3.14			      <
sphinx-book-theme             0.3.2			      <
sphinx-copybutton             0.5.0			      <
sphinx-panels                 0.6.0			      <
sphinxcontrib-applehelp       1.0.2			      <
sphinxcontrib-devhelp         1.0.2			      <
sphinxcontrib-htmlhelp        2.0.0			      <
sphinxcontrib-jsmath          1.0.1			      <
sphinxcontrib-qthelp          1.0.3			      <
sphinxcontrib-serializinghtml 1.1.5			      <
stack-data                    0.3.0			      <
terminado                     0.15.0			      <
tinycss2                      1.1.1			      <
tornado                       6.2			      |	tornado            6.1
traitlets                     5.3.0			      |	traitlets          5.1.1
typing_extensions             4.3.0			      |	urllib3            1.26.10
uc-micro-py                   1.0.1			      <
urllib3                       1.26.9			      <
webencodings                  0.5.1			      <
							      >	wheel              0.37.1
```

**Comment by damianavila** [comment]
Wondering if we should be more strict at the time to define the environment... 🤔

**Comment by sgibson91** [comment]
I'm not sure. I have a sinking feeling this is a deeper, system library issue. Maybe trying with a fresh conda environment would help?

**Comment by yuvipanda** [comment]
I wiped out my venv and set it up again, and boom this was gone!

Thanks for helping debug this, @sgibson91!
