### ISSUE TITLE
LEAP prod hub unable to start Large profile notebooks

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2237]
### Context

Filed through support. 

Get  a ValueError when spawning `Expected option gpu-image for profile large, not found in posted form`

**Comment by pnasrat** [comment]
```pytb
[W 2023-02-21 17:07:50.443 JupyterHub base:1039] 2 consecutive spawns failed.  Hub will exit if failure count reaches 5 before succeeding
[E 2023-02-21 17:07:50.443 JupyterHub gen:630] Exception in Future <Task finished name='Task-439647' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py:963> exception=ValueError('Expected option gpu-image for profile large, not found in posted form')> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/gen.py", line 625, in error_callback
        future.result()
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 970, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 851, in spawn
        raise e
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/user.py", line 748, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/jovyan/.local/lib/python3.11/site-packages/jupyterhub_configurator/mixins.py", line 45, in start
        return await super().start(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/kubespawner/spawner.py", line 2645, in _start
        await self.load_user_options()
      File "/usr/local/lib/python3.11/site-packages/kubespawner/spawner.py", line 3103, in load_user_options
        await self._load_profile(selected_profile, selected_profile_user_options)
      File "/usr/local/lib/python3.11/site-packages/kubespawner/spawner.py", line 3034, in _load_profile
        raise ValueError(
    ValueError: Expected option gpu-image for profile large, not found in posted form
    
[E 2023-02-21 17:07:50.449 JupyterHub pages:373] Previous spawn for pnasrat failed: Expected option gpu-image for profile large, not found in posted form
```

**Comment by pnasrat** [comment]
```
kubectl get nodes -n prod
NAME                                       STATUS   ROLES    AGE     VERSION
gke-leap-cluster-core-pool-1cc6bf7d-5fnp   Ready    <none>   130d    v1.24.5-gke.600
gke-leap-cluster-core-pool-1cc6bf7d-5fwt   Ready    <none>   62d     v1.24.5-gke.600
gke-leap-cluster-core-pool-1cc6bf7d-7wg2   Ready    <none>   31d     v1.24.5-gke.600
gke-leap-cluster-nb-huge-cf099c13-pplg     Ready    <none>   68m     v1.24.5-gke.600
gke-leap-cluster-nb-medium-b9c8ba20-45v5   Ready    <none>   3h28m   v1.24.5-gke.600
gke-leap-cluster-nb-medium-b9c8ba20-c6gs   Ready    <none>   137m    v1.24.5-gke.600
gke-leap-cluster-nb-medium-b9c8ba20-xdtg   Ready    <none>   136m    v1.24.5-gke.600
```

**Comment by pnasrat** [comment]
The traceback looks to be in profile handling - specifidcally for profile_options.

The form posts:

```
small-image: pangeo
profile-option-medium-image: pangeo
profile: large
profile-option-large-image: pangeo
profile-option-huge-image: pangeo
profile-option-large-gpu-image: tensorflow
```

See https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L3034

```python
        if profile.get('profile_options'):
            # each option specified here *must* have a value in our POST, as we
            # render our HTML such that there's always something selected.

            # We only honor options that are defined in the selected profile *and*
            # are in the form data posted. This prevents users who may be authorized
            # to only use one profile from being able to access options set for other
            # profiles
            for user_selected_option_name in selected_profile_user_options.keys():
                if (
                    user_selected_option_name
                    not in profile.get('profile_options').keys()
                ):
                    raise ValueError(
                        f'Expected option {user_selected_option_name} for profile {slug}, not found in posted form'
                    )
```

**Comment by pnasrat** [comment]
It doesn't look like the kubespawner side of this has changed lately but I suspect something is not working correctly having

profile-option-large-image
profile-option-large-gpu-image

**Comment by pnasrat** [comment]
It looks like potentially there was a change to how profile_options were configured in this commit by @yuvipanda in f20aa17c24955f2200b39595b215f3423cfe0165

**Comment by pnasrat** [comment]
That might be a red herring - trying to understand the flow

The form post will yield 

```python
{'profile': 'large',
 'profile-option-large-image': 'pangeo',
 'profile-option-large-gpu-image': 'tensorflow'}
```

This then gets parsed to be the options per profile ie having image and gpu-image for profile large.

**Comment by pnasrat** [comment]
Looking for hubs with profile lists with GPU 

```
ack -- '\+ GPU' 
m2lines/common.values.yaml
129:        - display_name: Large + GPU

leap/common.values.yaml
156:        - display_name: Large + GPU

2i2c-aws-us/researchdelight.values.yaml
79:        - display_name: "Large + GPU"
```

I tried on researchdelight and it worked, however the display name for large means the slug is `profile-item-large-m5-2xlarge`

```
 grep Large 2i2c-aws-us/researchdelight.values.yaml leap/common.values.yaml m2lines/common.values.yaml 
2i2c-aws-us/researchdelight.values.yaml:        - display_name: "Large: m5.2xlarge"
2i2c-aws-us/researchdelight.values.yaml:        - display_name: "Large + GPU"
leap/common.values.yaml:        - display_name: Large
leap/common.values.yaml:        - display_name: Large + GPU
m2lines/common.values.yaml:        - display_name: Large
m2lines/common.values.yaml:        - display_name: Large + GPU
```

**Comment by pnasrat** [comment]
I suspect either setting `slug` or changing the display name might work around this.  PR to test. I'm also pulling down minikube to test kubespawner's logic (based on the unit tests of the spawner using a mock spawner)

**Comment by pnasrat** [comment]
Modified the kubespawner unit tests to replicate this failure

```python
_test_profiles = [
    {
        'display_name': 'Training Env - Python',
        'slug': 'training-python',
        'default': True,
        'kubespawner_override': {
            'image': 'training/python:label',
            'cpu_limit': 1,
            'mem_limit': 512 * 1024 * 1024,
        },
    },
    {
        'display_name': 'Training Env - Datascience',
        'slug': 'training-python-datascience',
        'kubespawner_override': {
            'image': 'training/datascience:label',
            'cpu_limit': 4,
            'mem_limit': 8 * 1024 * 1024 * 1024,
        },
    },
]


async def test_user_options_set_from_form():
    spawner = KubeSpawner(_mock=True)
    spawner.profile_list = _test_profiles
    # render the form
    await spawner.get_options_form()
    spawner.user_options = {
            'profile': [_test_profiles[0]['slug']],
            f"{_test_profiles[1]['slug']}-image": "foo",
            f"{_test_profiles[0]['slug']}-image": "bar"
        }
    
    
   # assert spawner.user_options == {
   #     'profile': _test_profiles[1]['slug'],
   # }
    # nothing should be loaded yet
    assert spawner.cpu_limit is None
    await spawner.load_user_options()
    for key, value in _test_profiles[1]['kubespawner_override'].items():
        assert getattr(spawner, key) == value
```

```pytb

self = <kubespawner.spawner.KubeSpawner object at 0x7f8c22f34400>, slug = ['training-python']
selected_profile_user_options = {'training-python-datascience-image': 'foo', 'training-python-image': 'bar'}

    async def _load_profile(self, slug, selected_profile_user_options):
        """Load a profile by name
    
        Called by load_user_options
        """
    
        # find the profile
        default_profile = self._profile_list[0]
        for profile in self._profile_list:
            if profile.get('default', False):
                # explicit default, not the first
                default_profile = profile
    
            if profile['slug'] == slug:
                break
        else:
            if slug:
                # name specified, but not found
>               raise ValueError(
                    "No such profile: %s. Options include: %s"
                    % (slug, ', '.join(p['slug'] for p in self._profile_list))
                )
E               ValueError: No such profile: ['training-python']. Options include: training-python, training-python-datascience

kubespawner/spawner.py:3011: ValueError
```

**Comment by pnasrat** [comment]
Deleted prior kubespawner comment as not properly wired the test data.

**Comment by consideRatio** [comment]
Thanks for excellent overview of your investigation!

In the spawn page, pressing start on the large option, I found that the sent form data:

![image](https://user-images.githubusercontent.com/3837114/220551769-8fc0b68d-adc4-4d85-a8a4-eb080c70ee98.png)

So, all options are passed, but only the "large" is relevant. But when kubespawner consideres these options, we have a failure because it reacts on the `profile-option-large-gpu-image` option as it was a problem - an option beloning to the `large` profile as compared to the `large-gpu` profile.

I assume the issue is that kubespawner fail to distinguish between `<profile-name-slug-form>-<profile-option-slug-form>` because the separator can be part of the slug name as well.

I've confirmed this via this code segment, which just looks on a prefix. The `large` profile fails to start because its profile name is part of `large-gpu`.

https://github.com/jupyterhub/kubespawner/blob/main/kubespawner/spawner.py#L2981-L2991

I think the change that won't disrupt users is to add a `slug` (the name of the profile in a computer friendly format) that ensures `Large + GPU` doesn't get a similar slug to `large`, such as just `gpu`.

**Comment by consideRatio** [comment]
I opened https://github.com/jupyterhub/kubespawner/issues/702 but doesn't look to resolve it myself now that its documented well enough.

For us right now, the workaround should be to add a `slug` for the `Large + GPU` profile list entry so its not generated to be `large-gpu`, but to let it be declared like `gpu` or `gpu-large`.

Note that we should not try to combine the GPU profile_list entry with the Large server entry, as I know that we want to start using `n2-highmem` servers for non-gpu servers, but they can't have GPUs etc.

**Comment by pnasrat** [comment]
Deployer failed on LEAP staging health check but checking the staging hub the change is there and the hub is healthy. Will check manually.

**Comment by pnasrat** [comment]
Restarting the workflow failed jobs succeeded the health check, if this is recurrent we might need to revisit the retry strategy to not have flaky failures due to slow bringup
