### ISSUE TITLE
Failure to save notebooks due to issues with jupyter_server_fileid on jupyterlab >= 3.6

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2244]
Based on report in https://2i2c.freshdesk.com/a/tickets/476, me and @pnasrat had a debugging session trying to figure out why File saving is broken for some users (turned out to be very few!) on the UToronto hub as a result of #2240.

Our conclusions are:

1. JupyterLab 3.6 brings in something called [ydoc](https://github.com/jupyter-server/jupyter_ydoc), related to real time collab
2. This brings in a fileid server extension (that wasn't present in 3.5) - https://github.com/jupyter-server/jupyter_server_fileid
3. This puts file ids on a sqlite db
4. This is on the critical save path - if there are any failures here, no notebooks can be saved
5. And there was failures
```
[W 2023-02-22 14:05:53.096 SingleUserLabApp manager:359] jupyter_server_fileid | extension failed loading with message: unable to open database file
[E 2023-02-22 14:05:53.096 SingleUserLabApp manager:360] jupyter_server_fileid | stack trace
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 355, in load_extension
        extension.load_all_points(self.serverapp)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 229, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 229, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 222, in load_point
        return point.load(serverapp)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 148, in load
        return loader(serverapp)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 453, in _load_jupyter_server_extension
        extension.initialize()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 420, in initialize
        self._prepare_settings()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 302, in _prepare_settings
        self.initialize_settings()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_fileid/extension.py", line 23, in initialize_settings
        file_id_manager = self.file_id_manager_class(
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_fileid/manager.py", line 244, in __init__
        self.con.execute("PRAGMA journal_mode = WAL")
    sqlite3.OperationalError: unable to open database file
```
6. So we should find a way to report this upstream - this extension is in the critical path of file saving even if we do not touch real time collaboration at all
7. sqlite and NFS do not like each other
8. In the meantime, we can unblock utoronto by pinning to jupyterlab < 3.6

**Comment by yuvipanda** [comment]
@pnasrat also found https://www.sqlite.org/wal.html, which states WAL will not work over network filesystems. It fails arbitrarily. 

In general, I also think the fileid stuff should not be enabled unless you are doing RTC?

**Comment by yuvipanda** [comment]
Created https://github.com/2i2c-org/infrastructure/issues/2245 to track getting rid of sqlite from NFS

**Comment by yuvipanda** [comment]
Reported https://github.com/jupyter-server/jupyter_server_fileid/issues/60 upstream

**Comment by david-yz-liu** [comment]
BTW, I think the issue title should be `>= 3.6`?

**Comment by yuvipanda** [comment]
As a note, based on https://github.com/jupyter-server/jupyter_server_fileid/issues/60#issuecomment-1444605208, this could also have been the `nbsignatures.db` file causing issues, rather than the file_id file.

This brings up the question of why these failed at all, which could just be NFS being NFS. 

This also means https://github.com/2i2c-org/infrastructure/issues/2245 is decently important if we want to avoid a repeat.

**Comment by pnasrat** [comment]
Given #2245 is filed and the issue has been reported upstream I believe this can be closed, but putting in Waiting for the moment

**Comment by damianavila** [comment]
I agree, closing it.
