### ISSUE TITLE
Get all sqlite DBs off NFS

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2245]
### Context

Jupyter uses a couple of sqlite DBs:

1. [nbsignatures.db](https://jupyter-notebook.readthedocs.io/en/stable/security.html#the-details-of-trust) for managing trusted notebooks
2. (NEW!) [file_id_manager.db](https://github.com/jupyter-server/jupyter_server_fileid), for handling file ids for real time collaboration.

By default, these end up on the jupyter *data* path (not runtime path), as they (maybe? someone should verify) need to persist between sessions.

However, that menas they end up in `~/.local/share/jupyter`, which is on NFS.

NFS and sqlite kinda hate each other, and generally using them together causes problems that are hard to debug yet inevitable. So we should find a way to get these off NFS.

This was triggered by https://github.com/2i2c-org/infrastructure/issues/2244.

### Proposal

1. Figure out if we need nbsignatures.db to persist across sessions at all in our context (hosted jupyterhub). If we don't, let's put it in /tmp or somewhere else. If we do, let's document this.
2. Figure out if we can turn off the fileid sqlite db unless it is absolutely required for RTC. And even in that case, it can *not* exist on NFS - it uses WAL, which is not supported. So I guess we should just turn this off.

**Comment by yuvipanda** [comment]
https://github.com/jupyter-server/jupyter_server_fileid/issues/60 reported upstream

**Comment by consideRatio** [comment]
I'm unsure if there is an action point on us regarding this to track here, I'm pre-emptively closing this rather than keeping it around pending that.

- [x] We have avoided the issue
- [x] We have provided sufficient comments in our basehub config about how its being avoided

The remaining action point if any as I see it, is to follow https://github.com/jupyter-server/jupyter_server_fileid/issues/60 for updates that makes us think if we want to do something else.

**Comment by yuvipanda** [comment]
I was looking at the logs from the UToronto incident, and see similar messages posted for nbsignatures.db too:

```
[I 2023-02-22 14:27:39.397 SingleUserLabApp contentsmanager:138] Saving Untitled1.ipynb
[E 2023-02-22 14:27:39.407 SingleUserLabApp filemanager:449] Error while saving file: Untitled1.ipynb unable to open database file
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 434, in save
        self.check_and_sign(nb, path)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 651, in check_and_sign
        self.notary.sign(nb)
      File "/opt/conda/lib/python3.10/site-packages/nbformat/sign.py", line 453, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/opt/conda/lib/python3.10/site-packages/nbformat/sign.py", line 193, in store_signature
        if not self.check_signature(digest, algorithm):
      File "/opt/conda/lib/python3.10/site-packages/nbformat/sign.py", line 228, in check_signature
        self.db.execute(
    sqlite3.OperationalError: unable to open database file
[E 2023-02-22 14:27:39.408 SingleUserLabApp contentsmanager:178] Error while saving file: Untitled1.ipynb HTTP 500: Internal Server Error (Unexpected error while saving file: Untitled1.ipynb unable to open database file)
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 434, in save
        self.check_and_sign(nb, path)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/manager.py", line 651, in check_and_sign
        self.notary.sign(nb)
      File "/opt/conda/lib/python3.10/site-packages/nbformat/sign.py", line 453, in sign
        self.store.store_signature(signature, self.algorithm)
      File "/opt/conda/lib/python3.10/site-packages/nbformat/sign.py", line 193, in store_signature
        if not self.check_signature(digest, algorithm):
      File "/opt/conda/lib/python3.10/site-packages/nbformat/sign.py", line 228, in check_signature
        self.db.execute(
    sqlite3.OperationalError: unable to open database file
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupytext/contentsmanager.py", line 175, in save
        return write_pair(path, jupytext_formats, save_one_file)
      File "/opt/conda/lib/python3.10/site-packages/jupytext/pairs.py", line 38, in write_pair
        value = write_one_file(alt_path, fmt)
      File "/opt/conda/lib/python3.10/site-packages/jupytext/contentsmanager.py", line 142, in save_one_file
        return self.super.save(
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/largefilemanager.py", line 59, in save
        return super().save(model, path)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 450, in save
        raise web.HTTPError(500, f"Unexpected error while saving file: {path} {e}") from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Unexpected error while saving file: Untitled1.ipynb unable to open database file)
[W 2023-02-22 14:27:39.408 SingleUserLabApp web:1796] 500 POST /user/7c76d04b-2a80-4db1-b985-a2d2fa2f708c/api/contents (10.1.0.15): Unexpected error while saving file: Untitled1.ipynb HTTP 500: Internal Server Error (Unexpected error while saving file: Untitled1.ipynb unable to open database file)
[W 2023-02-22 14:27:39.408 SingleUserLabApp handlers:649] wrote error: 'Unexpected error while saving file: Untitled1.ipynb HTTP 500: Internal Server Error (Unexpected error while saving file: Untitled1.ipynb unable to open database file)'
```

(that is my user logs).
