### ISSUE TITLE
[lis] Investigate user report of kernel does not exist

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2359]
### Context

Reported via https://2i2c.freshdesk.com/a/tickets/547

User server reporting kernel does not exist

I logged into server and worked for me.

![image](https://user-images.githubusercontent.com/13798/225385990-dc85954d-7fe6-463c-b1f2-e82864fe5bd7.png)

```
99639058 (10.154.0.52): Kernel does not exist: 62e648e2-f524-408c-b53e-1af21e3fbcd3
[W 2023-03-15 17:00:39.132 SingleUserLabApp handlers:738] wrote error: 'Kernel does not exist: 62e648e2-f524-408c-b53e-1af21e3fbcd3'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 72, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 496, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 527, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
```

**Comment by pnasrat** [comment]
Google Logs Explorer query


```
resource.type="k8s_container"
resource.labels.namespace_name="lis"
resource.labels.pod_name="jupyter-matthew-2dbrett"
textPayload=~"Kernel does not exist"
```

**Comment by pnasrat** [comment]
First failure 

```json
{
  "textPayload": "[W 2023-03-15 16:24:50.388 SingleUserLabApp web:1796] 404 GET /user/matthew-brett/api/kernels/b560b61e-57c4-4308-a3d8-9f3c159fea27?1678897490300 (10.154.0.52): Kernel does not exist: b560b61e-57c4-4308-a3d8-9f3c159fea27",
  "insertId": "ep7g279ua0u83cjz",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "two-eye-two-see-uk",
      "namespace_name": "lis",
      "cluster_name": "two-eye-two-see-uk-cluster",
      "pod_name": "jupyter-matthew-2dbrett",
      "container_name": "notebook",
      "location": "europe-west2"
    }
  },
  "timestamp": "2023-03-15T16:24:50.388977704Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/release": "lis",
    "k8s-pod/hub_jupyter_org/username": "matthew-2dbrett",
    "k8s-pod/heritage": "jupyterhub",
    "k8s-pod/chart": "jupyterhub-2.0.1-0.dev.git.5987.h46a632f5",
    "compute.googleapis.com/resource_name": "gke-two-eye-two-see-uk-cluste-nb-user-893a49dd-wxhq",
    "k8s-pod/app": "jupyterhub",
    "k8s-pod/hub_jupyter_org/network-access-hub": "true",
    "k8s-pod/component": "singleuser-server",
    "k8s-pod/hub_jupyter_org/servername": ""
  },
  "logName": "projects/two-eye-two-see-uk/logs/stderr",
  "receiveTimestamp": "2023-03-15T16:24:52.321358327Z"
}
```

**Comment by pnasrat** [comment]
OOMs

https://grafana.uk.2i2c.cloud/d/gVxNqwHVk/cluster-information?orgId=1&viewPanel=13&from=1678879701140&to=1678901301140

![image](https://user-images.githubusercontent.com/13798/225392315-abc31a73-221f-43ca-aeb3-bc5bf9a15563.png)

**Comment by pnasrat** [comment]
OOM logs

<details>
<summary>OOM Logs:</summary>



```json
[
  {
    "textPayload": "[195998.443208] node invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=991\\r\\n",
    "insertId": "7710",
    "resource": {
      "type": "gce_instance",
      "labels": {
        "zone": "europe-west2-c",
        "instance_id": "4616395539098064229",
        "project_id": "two-eye-two-see-uk"
      }
    },
    "timestamp": "2023-03-15T15:50:35.927515678Z",
    "severity": "INFO",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-two-eye-two-see-uk-cluste-nb-user-893a49dd-wxhq",
      "is_text_escaped": "true"
    },
    "logName": "projects/two-eye-two-see-uk/logs/serialconsole.googleapis.com%2Fserial_port_1_output",
    "receiveTimestamp": "2023-03-15T15:50:37.933070466Z"
  },
  {
    "textPayload": "[196120.737205] ZMQbg/IO/0 invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=991\\r\\n",
    "insertId": "7810",
    "resource": {
      "type": "gce_instance",
      "labels": {
        "instance_id": "4616395539098064229",
        "project_id": "two-eye-two-see-uk",
        "zone": "europe-west2-c"
      }
    },
    "timestamp": "2023-03-15T15:52:38.229654772Z",
    "severity": "INFO",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-two-eye-two-see-uk-cluste-nb-user-893a49dd-wxhq",
      "is_text_escaped": "true"
    },
    "logName": "projects/two-eye-two-see-uk/logs/serialconsole.googleapis.com%2Fserial_port_1_output",
    "receiveTimestamp": "2023-03-15T15:52:40.235787886Z"
  },
  {
    "textPayload": "[196230.671388] python invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=991\\r\\n",
    "insertId": "7905",
    "resource": {
      "type": "gce_instance",
      "labels": {
        "zone": "europe-west2-c",
        "instance_id": "4616395539098064229",
        "project_id": "two-eye-two-see-uk"
      }
    },
    "timestamp": "2023-03-15T15:54:28.171153047Z",
    "severity": "INFO",
    "labels": {
      "is_text_escaped": "true",
      "compute.googleapis.com/resource_name": "gke-two-eye-two-see-uk-cluste-nb-user-893a49dd-wxhq"
    },
    "logName": "projects/two-eye-two-see-uk/logs/serialconsole.googleapis.com%2Fserial_port_1_output",
    "receiveTimestamp": "2023-03-15T15:54:30.180922898Z"
  },
  {
    "textPayload": "[196421.940495] python invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=991\\r\\n",
    "insertId": "7977",
    "resource": {
      "type": "gce_instance",
      "labels": {
        "project_id": "two-eye-two-see-uk",
        "zone": "europe-west2-c",
        "instance_id": "4616395539098064229"
      }
    },
    "timestamp": "2023-03-15T15:57:39.453041790Z",
    "severity": "INFO",
    "labels": {
      "is_text_escaped": "true",
      "compute.googleapis.com/resource_name": "gke-two-eye-two-see-uk-cluste-nb-user-893a49dd-wxhq"
    },
    "logName": "projects/two-eye-two-see-uk/logs/serialconsole.googleapis.com%2Fserial_port_1_output",
    "receiveTimestamp": "2023-03-15T15:57:41.464249729Z"
  }
]
```
</details>
