### ISSUE TITLE
[lis] Student getting error 500 on login

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2410]
### Context

via https://2i2c.freshdesk.com/a/tickets/577

User gets error 500 on login

### Proposal

Logs https://cloudlogging.app.goo.gl/skHyJqGaCPeedtZDA

**Comment by pnasrat** [comment]
Note this seems fixed but the logs do show the below exception during exception handling. 

```pytb
    jinja2.exceptions.TemplateNotFound: notebook.html
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/tornado/gen.py", line 782, in run
        yielded = self.gen.send(value)
      File "/opt/conda/lib/python3.10/site-packages/nbclassic/notebook/handlers.py", line 101, in get
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 632, in render_template
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/handler.py", line 21, in get_template
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 627, in get_template
      File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
      File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
      File "/opt/conda/lib/python3.10/site-packages/jinja2/loaders.py", line 575, in load
    jinja2.exceptions.TemplateNotFound: notebook.html
[E 2023-03-22 14:45:08.861 SingleUserLabApp web:1221] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/handler.py", line 19, in get_template
      File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
      File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
      File "/opt/conda/lib/python3.10/site-packages/jinja2/loaders.py", line 575, in load
    jinja2.exceptions.TemplateNotFound: notebook.html
    
    During handling of the above exception, another exception occurred:
```

**Comment by pnasrat** [comment]
```
[E 2023-03-22 14:21:13.308 SingleUserLabApp web:1798] Uncaught exception GET /user/kijid/git-pull?repo=https%3A%2F%2Fgithub.com%2Ftexturejc%2Fword2vec&urlpath=tree%2Fword2vec%2F&redirects=1 (10.154.0.44)"
```

**Comment by yuvipanda** [comment]
A screenshot is often helpful here too, as it lets us know wether the 500 was happening from JupyterHub (the most common case) or from the user notebook.

**Comment by pnasrat** [comment]
I'm not sure what more can be done here as the original issue has resolved itself. Closing.
