### ISSUE TITLE
Cloud logging on GCP - ingested GB of logs an indication of an issue

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3016]
I saw a user pod that spammed error messages (2i2c cluster), and that made me think that it should probably incurr significant logging costs. Looking at all GCP clusters for a 2i2c billing account, only the 2i2c cluster had incurred costs. The first 50GB of ingested logs are free per month, so, only the 2i2c cluster had ingested more than 50GB logs in a month.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/d5e0b2e1-d277-436b-8067-fce00f996a63)

In practice, I think the 2i2c cluster have ingested around ~600GB of logs the last month. I think this amount of log ingestion is possibly related to a network speed slowdown as well as discussed in #2947.

<details>
<summary>Example of a repeating error from a user pod that had been running for more than a month</summary>

```
[E 2023-08-23 06:40:10.328 YDocExtension] Error watching file: course-content/book/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.ipynb
    TypeError("'<' not supported between instances of 'NoneType' and 'datetime.datetime'")
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/loaders.py", line 170, in _watch_file
        await self.notify()
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/loaders.py", line 187, in notify
        await callback("metadata", model)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/rooms.py", line 190, in _on_content_change
        if event == "metadata" and self._last_modified < args["last_modified"]:
    TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
[E 2023-08-23 06:40:11.329 YDocExtension] Error watching file: course-content/book/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.ipynb
    TypeError("'<' not supported between instances of 'NoneType' and 'datetime.datetime'")
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/loaders.py", line 170, in _watch_file
        await self.notify()
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/loaders.py", line 187, in notify
        await callback("metadata", model)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/rooms.py", line 190, in _on_content_change
        if event == "metadata" and self._last_modified < args["last_modified"]:
    TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
[E 2023-08-23 06:40:12.330 YDocExtension] Error watching file: course-content/book/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.ipynb
    TypeError("'<' not supported between instances of 'NoneType' and 'datetime.datetime'")
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/loaders.py", line 170, in _watch_file
        await self.notify()
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/loaders.py", line 187, in notify
        await callback("metadata", model)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_collaboration/rooms.py", line 190, in _on_content_change
        if event == "metadata" and self._last_modified < args["last_modified"]:
    TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'
```

</details>

**Comment by colliand** [comment]
Thanks @consideRatio for noticing the log explosion and culling the abandoned processes. Is there a diagnosis or hypothesis for why this occurred?

**Comment by consideRatio** [comment]
I found metrics in GCP about the log ingestion rate, and it has been at a few MiB/s. For example between 17 july and 20 july, the ingestion rate was ~2-3 MiB/s on average based on [this dashboard on GCP](https://console.cloud.google.com/monitoring/metrics-explorer;startTime=2023-07-17T11:03:23.523Z;endTime=2023-07-21T18:33:55.015Z?pageState=%7B%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%5D,%22perSeriesAligner%22:%22ALIGN_RATE%22%7D%5D,%22apiSource%22:%22DEFAULT_CLOUD%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22filter%22:%22metric.type%3D%5C%22logging.googleapis.com%2Fbilling%2Fbytes_ingested%5C%22%20resource.type%3D%5C%22global%5C%22%22,%22groupByFields%22:%5B%5D,%22minAlignmentPeriod%22:%2260s%22,%22perSeriesAligner%22:%22ALIGN_RATE%22%7D%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22y1Axis%22:%7B%22label%22:%22%22,%22scale%22:%22LINEAR%22%7D%7D%7D&project=two-eye-two-see&authuser=3).

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/007ac1b3-3b2a-4f06-a60b-491c30adc300)

There have been ingestion rates of tens of MiB/s during individual minutes, for example august 15th between 6-7 PM UTC time when we had this massive spike, as seen when zooming in:

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/2cb8e713-077a-4cf7-b29d-ba7939fd3753)

**Comment by yuvipanda** [comment]
Thanks for digging into this, @consideRatio!

Can we write a rule that abandones user pod logs after about a day, or perhaps just not ingest them at all to deal with this for now?

**Comment by consideRatio** [comment]
> Can we write a rule that abandones user pod logs after about a day

I think this would be to create a user defined log retention rule: https://cloud.google.com/logging/quotas#logs_retention_periods

> or perhaps just not ingest them at all to deal with this for now?

Based on the comment below, it seems that there is a difference between not reading them at all, and storing them.

> Log entries are excluded after they are received by the Logging API and therefore these log entries consume [entries.write API quota](https://cloud.google.com/logging/quotas#api-limits). You can't reduce the number of [entries.write API calls](https://cloud.google.com/logging/quotas#log-limits) by excluding log entries.

Its possible to create an exclusion rule for storing them via an ["exclusion filter"](https://cloud.google.com/logging/docs/routing/overview#exclusions) for the "_Default" logging sink. Here is a [GCP Console link to trial doing that](https://console.cloud.google.com/logs/router/sink/projects%2Ftwo-eye-two-see%2Fsinks%2F_Default?project=two-eye-two-see).

If user logs are excluded from the `_Default` logging sink, then I guess they can be included in a custom logging sink if we set that up, to have shorter retention than 30 days for example.

---

I'm unassigning myself to indicate I'm not actively working to resolve this.
