### ISSUE TITLE
meom-ige's staging health check failing - user env issues?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3284]
```
kubectl logs -n staging jupyter-deployment-2dservice-2dcheck

...

[E 2023-10-18 05:33:35.167 JupyterHubSingleUser] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 425, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```

<summary>
<details>All logs up to the forbidden error</details>

```
Defaulted container "notebook" out of: notebook, volume-mount-ownership-fix (init)
[I 2023-10-18 05:23:49.979 ServerApp] Package jupyterhub took 0.0000s to import
[I 2023-10-18 05:23:50.031 ServerApp] Package jupyter_lsp took 0.0490s to import
[W 2023-10-18 05:23:50.032 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-18 05:23:50.055 ServerApp] Package jupyter_server_terminals took 0.0220s to import
[I 2023-10-18 05:23:50.261 ServerApp] Package jupyterlab took 0.2030s to import
[I 2023-10-18 05:23:51.741 ServerApp] Package nbclassic took 0.0039s to import
[W 2023-10-18 05:23:51.743 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-18 05:23:51.744 ServerApp] Package notebook took 0.0000s to import
[I 2023-10-18 05:23:51.747 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-10-18 05:23:51.747 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-10-18 05:23:51.748 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-10-18 05:23:51.756 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-10-18 05:23:51.757 JupyterHubSingleUser] Starting jupyterhub single-user server extension version 4.0.2
[I 2023-10-18 05:23:51.757 JupyterHubSingleUser] Using default url from environment $JUPYTERHUB_DEFAULT_URL: /lab
[I 2023-10-18 05:23:51.767 ServerApp] jupyterhub | extension was successfully linked.
[W 2023-10-18 05:23:51.773 LabApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[I 2023-10-18 05:23:51.784 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-10-18 05:23:51.790 NotebookApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2023-10-18 05:23:51.791 NotebookApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[I 2023-10-18 05:23:51.799 ServerApp] nbclassic | extension was successfully linked.
[W 2023-10-18 05:23:51.803 JupyterNotebookApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2023-10-18 05:23:51.804 JupyterNotebookApp] 'extra_template_paths' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[I 2023-10-18 05:23:51.811 ServerApp] notebook | extension was successfully linked.
[I 2023-10-18 05:23:51.814 ServerApp] Writing Jupyter server cookie secret to /tmp/.jupyter-runtime/jupyter_cookie_secret
[I 2023-10-18 05:23:52.284 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-10-18 05:23:52.329 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-10-18 05:23:52.335 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-10-18 05:23:52.337 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-10-18 05:23:52.351 JupyterHubSingleUser] Updating Hub with activity every 300 seconds
[I 2023-10-18 05:23:52.352 ServerApp] jupyterhub | extension was successfully loaded.
[I 2023-10-18 05:23:52.360 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2023-10-18 05:23:52.365 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2023-10-18 05:23:52.367 LabApp] Extension Manager is 'pypi'.
[I 2023-10-18 05:23:52.376 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-10-18 05:23:52.394 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-10-18 05:23:52.403 ServerApp] notebook | extension was successfully loaded.
[I 2023-10-18 05:23:52.405 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2023-10-18 05:23:52.405 ServerApp] Jupyter Server 2.8.0 is running at:
[I 2023-10-18 05:23:52.406 ServerApp] http://jupyter-deployment-2dservice-2dcheck:8888/user/deployment-service-check/lab?token=...
[I 2023-10-18 05:23:52.407 ServerApp]     http://127.0.0.1:8888/user/deployment-service-check/lab?token=...
[I 2023-10-18 05:23:52.407 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2023-10-18 05:23:54.101 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[E 2023-10-18 05:33:35.167 JupyterHubSingleUser] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 425, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2023-10-18 05:33:35.850 JupyterHubSingleUser] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 425, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2023-10-18 05:33:37.590 JupyterHubSingleUser] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 425, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2023-10-18 05:33:40.534 JupyterHubSingleUser] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 425, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
[E 2023-10-18 05:33:48.152 JupyterHubSingleUser] Error notifying Hub of activity
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 425, in notify
        await client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```

</summary>

**Comment by consideRatio** [comment]
I think these errors showed up after the health check tests had stopped, 10 minutes after the pod started. So, this is probably not what caused the health check to fail. Closing this for now, not confident on what caused the original issue still and this no longer reproduces.

```
Running hub health check for staging...
Fetching cluster endpoint and auth data.
kubeconfig entry generated for meom-ige-cluster.
Testing locally, do not redirect output
.                                                                                                                                                  [100%]
1 passed in 148.04s (0:02:28)
Health check succeeded!
```

It seems though that pulling the jupyter/base-notebook:latest was very slow though, it took almost a minute and its only 300MB.

```
Successfully pulled image "jupyter/base-notebook:latest" in 58.592315511s (59.271738003s including waiting)
```
