### ISSUE TITLE
How to write to scratch and persistent buckets on a hub?

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#3639]
### Context

- ref: https://2i2c.freshdesk.com/a/tickets/1255

I was asked via support to set up scratch and persistent buckets for the showcase hub, and I did so in:

- https://github.com/2i2c-org/infrastructure/pull/3626
- https://github.com/2i2c-org/infrastructure/pull/3628

There was some confusion in the ticket because Jenny was expecting me to send her a `CLIENT_KEY` and `CLIENT_SECRET` according to https://docs.2i2c.org/user/topics/data/cloud/, but following https://infrastructure.2i2c.org/howto/features/buckets/ I found no mention of keys and secrets, and nothing I did generated any.

As far as I am aware, adding the bucket names to the `bucket_admin_access` section of the `hub_cloud_permissions` variable in terraform grants read/write permission to the bucket in a role that is passed to the hub via a kubernetes annotation. Every user server gets this annotation and reading/writing the bucket should "just work". However, Jenny has reported that she is unable to write to the bucket:

```
$ import os
$ import xarray as xr
$ SCRATCH_BUCKET = os.environ['SCRATCH_BUCKET'] 
$ ds = xr.tutorial.open_dataset("rasm")  # load example data
$ ds.to_zarr(f'{SCRATCH_BUCKET}/rasm.zarr')  # write data

Refreshing temporary credentials failed during mandatory refresh period.
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py", line 327, in _protected_refresh
    metadata = await self._refresh_using()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py", line 385, in fetch_credentials
    return await self._get_cached_credentials()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py", line 395, in _get_cached_credentials
    response = await self._get_credentials()
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py", line 469, in _get_credentials
    return await client.assume_role_with_web_identity(**kwargs)
  File "/srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/client.py", line 371, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
File /srv/conda/envs/notebook/lib/python3.10/site-packages/s3fs/core.py:113, in _error_wrapper(func, args, kwargs, retries)
    112 try:
--> 113     return await func(*args, **kwargs)
    114 except S3_RETRYABLE_ERRORS as e:

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/client.py:354, in AioBaseClient._make_api_call(self, operation_name, api_params)
    353     apply_request_checksum(request_dict)
--> 354     http, parsed_response = await self._make_request(
    355         operation_model, request_dict, request_context
    356     )
    358 await self.meta.events.emit(
    359     'after-call.{service_id}.{operation_name}'.format(
    360         service_id=service_id, operation_name=operation_name
   (...)
    365     context=request_context,
    366 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/client.py:379, in AioBaseClient._make_request(self, operation_model, request_dict, request_context)
    378 try:
--> 379     return await self._endpoint.make_request(
    380         operation_model, request_dict
    381     )
    382 except Exception as e:

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/endpoint.py:96, in AioEndpoint._send_request(self, request_dict, operation_model)
     95 self._update_retries_context(context, attempts)
---> 96 request = await self.create_request(request_dict, operation_model)
     97 success_response, exception = await self._get_response(
     98     request, operation_model, context
     99 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/endpoint.py:84, in AioEndpoint.create_request(self, params, operation_model)
     81     event_name = 'request-created.{service_id}.{op_name}'.format(
     82         service_id=service_id, op_name=operation_model.name
     83     )
---> 84     await self._event_emitter.emit(
     85         event_name,
     86         request=request,
     87         operation_name=operation_model.name,
     88     )
     89 prepared_request = self.prepare_request(request)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/hooks.py:66, in AioHierarchicalEmitter._emit(self, event_name, kwargs, stop_on_response)
     65 # Await the handler if its a coroutine.
---> 66 response = await resolve_awaitable(handler(**kwargs))
     67 responses.append((handler, response))

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/_helpers.py:15, in resolve_awaitable(obj)
     14 if inspect.isawaitable(obj):
---> 15     return await obj
     17 return obj

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/signers.py:24, in AioRequestSigner.handler(self, operation_name, request, **kwargs)
     19 async def handler(self, operation_name=None, request=None, **kwargs):
     20     # This is typically hooked up to the "request-created" event
     21     # from a client's event emitter.  When a new request is created
     22     # this method is invoked to sign the request.
     23     # Don't call this method directly.
---> 24     return await self.sign(operation_name, request)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/signers.py:73, in AioRequestSigner.sign(self, operation_name, request, region_name, signing_type, expires_in, signing_name)
     72 try:
---> 73     auth = await self.get_auth_instance(**kwargs)
     74 except UnknownSignatureVersionError as e:

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/signers.py:147, in AioRequestSigner.get_auth_instance(self, signing_name, region_name, signature_version, **kwargs)
    145 if self._credentials is not None:
    146     frozen_credentials = (
--> 147         await self._credentials.get_frozen_credentials()
    148     )
    149 kwargs['credentials'] = frozen_credentials

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py:358, in AioRefreshableCredentials.get_frozen_credentials(self)
    357 async def get_frozen_credentials(self):
--> 358     await self._refresh()
    359     return self._frozen_credentials

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py:312, in AioRefreshableCredentials._refresh(self)
    309 is_mandatory_refresh = self.refresh_needed(
    310     self._mandatory_refresh_timeout
    311 )
--> 312 await self._protected_refresh(
    313     is_mandatory=is_mandatory_refresh
    314 )
    315 return

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py:327, in AioRefreshableCredentials._protected_refresh(self, is_mandatory)
    326 try:
--> 327     metadata = await self._refresh_using()
    328 except Exception:

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py:385, in AioCachedCredentialFetcher.fetch_credentials(self)
    384 async def fetch_credentials(self):
--> 385     return await self._get_cached_credentials()

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py:395, in AioCachedCredentialFetcher._get_cached_credentials(self)
    394 if response is None:
--> 395     response = await self._get_credentials()
    396     self._write_to_cache(response)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/credentials.py:469, in AioAssumeRoleWithWebIdentityCredentialFetcher._get_credentials(self)
    468 async with self._client_creator('sts', config=config) as client:
--> 469     return await client.assume_role_with_web_identity(**kwargs)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/aiobotocore/client.py:371, in AioBaseClient._make_api_call(self, operation_name, api_params)
    370     error_class = self.exceptions.from_code(error_code)
--> 371     raise error_class(parsed_response, operation_name)
    372 else:

ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity

The above exception was the direct cause of the following exception:

PermissionError                           Traceback (most recent call last)
Cell In[3], line 1
----> 1 ds.to_zarr(f'{SCRATCH_BUCKET}/rasm.zarr')  # write data

File /srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/core/dataset.py:2141, in Dataset.to_zarr(self, store, chunk_store, mode, synchronizer, group, encoding, compute, consolidated, append_dim, region, safe_chunks, storage_options, zarr_version, chunkmanager_store_kwargs)
   2020 """Write dataset contents to a zarr group.
   2021 
   2022 Zarr chunks are determined in the following way:
   (...)
   2137     The I/O user guide, with more details and examples.
   2138 """
   2139 from xarray.backends.api import to_zarr
-> 2141 return to_zarr(  # type: ignore[call-overload,misc]
   2142     self,
   2143     store=store,
   2144     chunk_store=chunk_store,
   2145     storage_options=storage_options,
   2146     mode=mode,
   2147     synchronizer=synchronizer,
   2148     group=group,
   2149     encoding=encoding,
   2150     compute=compute,
   2151     consolidated=consolidated,
   2152     append_dim=append_dim,
   2153     region=region,
   2154     safe_chunks=safe_chunks,
   2155     zarr_version=zarr_version,
   2156     chunkmanager_store_kwargs=chunkmanager_store_kwargs,
   2157 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/backends/api.py:1672, in to_zarr(dataset, store, chunk_store, mode, synchronizer, group, encoding, compute, consolidated, append_dim, region, safe_chunks, storage_options, zarr_version, chunkmanager_store_kwargs)
   1670     already_consolidated = False
   1671     consolidate_on_close = consolidated or consolidated is None
-> 1672 zstore = backends.ZarrStore.open_group(
   1673     store=mapper,
   1674     mode=mode,
   1675     synchronizer=synchronizer,
   1676     group=group,
   1677     consolidated=already_consolidated,
   1678     consolidate_on_close=consolidate_on_close,
   1679     chunk_store=chunk_mapper,
   1680     append_dim=append_dim,
   1681     write_region=region,
   1682     safe_chunks=safe_chunks,
   1683     stacklevel=4,  # for Dataset.to_zarr()
   1684     zarr_version=zarr_version,
   1685 )
   1687 if mode in ["a", "r+"]:
   1688     _validate_datatypes_for_zarr_append(zstore, dataset)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/xarray/backends/zarr.py:445, in ZarrStore.open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close, chunk_store, storage_options, append_dim, write_region, safe_chunks, stacklevel, zarr_version)
    443     zarr_group = zarr.open_consolidated(store, **open_kwargs)
    444 else:
--> 445     zarr_group = zarr.open_group(store, **open_kwargs)
    446 return cls(
    447     zarr_group,
    448     mode,
   (...)
    452     safe_chunks,
    453 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/zarr/hierarchy.py:1455, in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store, storage_options, zarr_version, meta_array)
   1452         init_group(store, path=path, chunk_store=chunk_store)
   1454 elif mode in ['w-', 'x']:
-> 1455     if contains_array(store, path=path):
   1456         raise ContainsArrayError(path)
   1457     elif contains_group(store, path=path):

File /srv/conda/envs/notebook/lib/python3.10/site-packages/zarr/storage.py:108, in contains_array(store, path)
    106 prefix = _path_to_prefix(path)
    107 key = _prefix_to_array_key(store, prefix)
--> 108 return key in store

File /srv/conda/envs/notebook/lib/python3.10/site-packages/zarr/storage.py:1447, in FSStore.__contains__(self, key)
   1445 def __contains__(self, key):
   1446     key = self._normalize_key(key)
-> 1447     return key in self.map

File /srv/conda/envs/notebook/lib/python3.10/site-packages/fsspec/mapping.py:181, in FSMap.__contains__(self, key)
    179 """Does key exist in mapping?"""
    180 path = self._key_to_str(key)
--> 181 return self.fs.exists(path) and self.fs.isfile(path)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/fsspec/asyn.py:121, in sync_wrapper.<locals>.wrapper(*args, **kwargs)
    118 @functools.wraps(func)
    119 def wrapper(*args, **kwargs):
    120     self = obj or args[0]
--> 121     return sync(self.loop, func, *args, **kwargs)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/fsspec/asyn.py:106, in sync(loop, func, timeout, *args, **kwargs)
    104     raise FSTimeoutError from return_result
    105 elif isinstance(return_result, BaseException):
--> 106     raise return_result
    107 else:
    108     return return_result

File /srv/conda/envs/notebook/lib/python3.10/site-packages/fsspec/asyn.py:61, in _runner(event, coro, result, timeout)
     59     coro = asyncio.wait_for(coro, timeout=timeout)
     60 try:
---> 61     result[0] = await coro
     62 except Exception as ex:
     63     result[0] = ex

File /srv/conda/envs/notebook/lib/python3.10/site-packages/s3fs/core.py:1004, in S3FileSystem._exists(self, path)
   1001     return exists_in_cache
   1003 try:
-> 1004     await self._info(path, bucket, key, version_id=version_id)
   1005     return True
   1006 except FileNotFoundError:

File /srv/conda/envs/notebook/lib/python3.10/site-packages/s3fs/core.py:1271, in S3FileSystem._info(self, path, bucket, key, refresh, version_id)
   1269 if key:
   1270     try:
-> 1271         out = await self._call_s3(
   1272             "head_object",
   1273             self.kwargs,
   1274             Bucket=bucket,
   1275             Key=key,
   1276             **version_id_kw(version_id),
   1277             **self.req_kw,
   1278         )
   1279         return {
   1280             "ETag": out.get("ETag", ""),
   1281             "LastModified": out["LastModified"],
   (...)
   1287             "ContentType": out.get("ContentType"),
   1288         }
   1289     except FileNotFoundError:

File /srv/conda/envs/notebook/lib/python3.10/site-packages/s3fs/core.py:348, in S3FileSystem._call_s3(self, method, *akwarglist, **kwargs)
    346 logger.debug("CALL: %s - %s - %s", method.__name__, akwarglist, kw2)
    347 additional_kwargs = self._get_s3_method_kwargs(method, *akwarglist, **kwargs)
--> 348 return await _error_wrapper(
    349     method, kwargs=additional_kwargs, retries=self.retries
    350 )

File /srv/conda/envs/notebook/lib/python3.10/site-packages/s3fs/core.py:140, in _error_wrapper(func, args, kwargs, retries)
    138         err = e
    139 err = translate_boto_error(err)
--> 140 raise err

PermissionError: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

What is going on here? I don't actually know how researchers actually access/write to buckets and assumed this "just worked" since no one else has had issues, and I assumed I had done everything I needed to from the terraform/hub side of things. Can @2i2c-org/engineering provide any clarity?

**Comment by GeorgianaElena** [comment]
@sgibson91, found this https://github.com/2i2c-org/infrastructure/pull/1322#issuecomment-1138112551 that looks relevant and wanted to read on it.

**Comment by GeorgianaElena** [comment]
> I don't actually know how researchers actually access/write to buckets and assumed this "just worked" since no one else has had issues, 

Also, I'm in the same boat on the above ⬆️

**Comment by jnywong** [comment]
> @sgibson91, found this https://github.com/2i2c-org/infrastructure/pull/1322#issuecomment-1138112551 that looks relevant and wanted to read on it.

I dunno if this helps but in reference to the above, I tried the following in the Showcase Hub and got:

```bash
(notebook) jovyan@jupyter-jnywong:~$ aws sts assume-role-with-web-identity \
 --role-arn $AWS_ROLE_ARN \
 --role-session-name $JUPYTERHUB_CLIENT_ID \
 --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE

An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

**Comment by damianavila** [comment]
@yuvipanda or @consideRatio, do you have any furhter thoughts about this one?

**Comment by consideRatio** [comment]
## Issue 1 - our docs isn't explicit enough

I think our [working with object storage docs](https://docs.2i2c.org/user/topics/data/cloud/#working-with-object-storage) should explicitly distinguish the following scenarios:

1. __its a 2i2c hub's user environment and its 2i2c hub's associated cloud bucket__

   In this case, writing data should work straight away as credentials should be setup and available for the user as long as the user environment image has relevant cloud CLI tools installed like `aws`, `gcloud`, or `az`.
   
   I know that the `pangeo/pangeo-notebook` is an image that includes the `aws` CLI of relevance for the showcase hub with an AWS bucket.

2. __its their environment / laptop and its 2i2c hub's associated cloud bucket__
   In this case, they need to acquire and configure credentials manually first. They could either get temporary credentials by extracting such from a 2i2c user environment, or use dedicated credentials in the cloud project setup for them personally.
   
   Extracting temporary credentials is discussed in https://github.com/2i2c-org/infrastructure/issues/2096 and isn't an established  and user friendly procedure yet.

3. __its their environment / laptop and its their cloud bucket__

   I don't think its in scope for 2i2c to help with this or write docs focused on this situation.

## Issue 2 - access to showcase hub's scratch bucket

I've attempted to use the code snippet from our [docs on scratch buckets](https://docs.2i2c.org/user/topics/data/cloud/#scratch-bucket) and also got an error.

```python
import os
import xarray as xr
SCRATCH_BUCKET = os.environ['SCRATCH_BUCKET'] 
ds = xr.tutorial.open_dataset("rasm")  # load example data
ds.to_zarr(f'{SCRATCH_BUCKET}/rasm.zarr')  # write data
```

Using the more direct test of `aws s3 ls $SCRATCH_BUCKET` I've concluded that there is an auth issue to handle for the showcase hub.

Like @sgibson91 and @GeorgianaElena, my expectation is that permissions to access the scratch bucket should be setup automatically.

## Debugging issue 2

So how do I get `aws s3 ls $SCRATCH_BUCKET` to run successfully in a terminal?

### Explicit understanding

My understanding is that for bucket permissions to be provided to the user servers' users by:

1. user pods should reference a k8s ServiceAccount
2. the k8s ServiceAccount should via annotation reference an AWS role or similar granting relevant permissions
3. behind the scenes: aws has registered a "mutating webhook" to modify pod specifications before they are registered, and it modifies pod specifications referencing k8s ServiceAcconts with aws specific annotations so that they get mounted credentials
   ```yaml
    # a volume is added to the pod
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token

    # a volumeMount is added to the pod's user server container
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
   ```
4. (assumption) `aws` as a CLI will be able to make use of these credentials without further commands

### What fails?

1. I've seen `/var/run/secrets/eks.amazonaws.com/serviceaccount` in a showcase user pod, the available credentials seem to have propegated properly to there.
2. I think what fails is that we lack the relevant permissions, specifically the permission to `sts:AssumeRoleWithWebIdentity`, based on `An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity`.
   Why? I'll have a look in terraform config and verify the state is matching the config. To be continued...

**Comment by jnywong** [comment]
Thanks for the update @consideRatio ! I will definitely take the lessons learned from this to update the Service Docs accordingly.

**Comment by consideRatio** [comment]
> Thanks for the update @consideRatio ! I will definitely take the lessons learned from this to update the Service Docs accordingly.

Thank you @jnywong!!! I opened #3663 to extract "Issue 1" from this issue that I closed as part of verifying that bucket access was once again functioning.
