### ISSUE TITLE
Manually test the upgrade to z2jh 4 on a few hubs

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#5211]
Checkout the changes in the PR generated by https://github.com/2i2c-org/infrastructure/issues/5210 and manually deploy them to:

- [x] `2i2c-staging` hub, a hub that uses CILogon with Google 
- [x]  `2i2c dask-staging` hub, a daskhub
- [x] `2i2c imagebuilding-demo`, an image building hub with auth and a hub that uses GitHubOAuthenticator directly
- [x] `opensci small-binder`, an image building hub without auth
- [x] `earthscope-staging`, a hub that uses CILogon with GitHub already have jmte staging for this test case
- [x] ~`jupyter-health staging`~ not needed as we're not removing its experiment image
- [x] `jmte staging` - has shared-public and existing named servers
- [x] `openscapes-staging`, a hub that uses an user image with JupyterHub 4
- [x] ~`leap-staging` - has existing named servers~
- [x] `utoronto-staging` - for nbgitpuller
- [x] `opensci climaterisk` - shared password hub 
- [x] do one more check with a user image running jupyterhub3. The one I did was on a binderhub

Then manually test:

- [x] Authentication
- [x]  Server spawn
- [x]  Home directory names are preserved 
- [x] The configurator still works
- [x]  Executing a notebook works
- [x] Starting RStudio works
- [x] Dask works
- [x] Profile lists
- [x] Named servers, particularly ones with weird chars in their names (starting with capitals, etc)
- [x] Existing named servers of people to see if it starts (I suggest looking at the admins on LEAP)
- [x] Check shared, shared-readwrite and shared_public, making sure admins can write to shared-readwrite and others can only read from shared
- [x] Bringing your own docker image works
- [x] Shared password hub
- [x] deployer health checks, both for regular hubs and binderhub deploys (I think you've already tested these)
- [x] nbgitpuller links work (Yuvi recommends testing this on utoronto hubs)

### Definition of Done

The hubs mentioned have been passing all manual tests while using z2jh v4 chart

**Comment by yuvipanda** [comment]
- Test named servers, particularly ones with weird chars in their names (starting with capitals, etc)
- Test *existing* named servers of people to see if it starts (I suggest looking at the admins on LEAP)
- Check shared, shared-readwrite and shared_public, making sure admins can write to shared-readwrite and others can only read from shared
- Bringing your own docker image works
- Shared password hub
- deployer health checks, both for regular hubs and binderhub deploys (I think you've already tested these)
- nbgitpuller links work (I recommend testing this on utoronto hubs)

**Comment by GeorgianaElena** [comment]
> Named servers, particularly ones with weird chars in their names (starting with capitals, etc)

I tried different kind of odd names and the only one that didn't work, were `.`, `/`, `#` (404 error),  any name starting with `%`(400 error)

<img width="1322" alt="Image" src="https://github.com/user-attachments/assets/4bb02479-13db-4387-a5eb-88eefbaf3873" />

> Test existing named servers of people to see if it starts (I suggest looking at the admins on LEAP)

Found one `test` on the jtme stating from @yuvipanda and started that instead and it worked.

**Comment by GeorgianaElena** [comment]
Tested on the imagebuilding hub the following:
- starting an image running jupyterhub-singleuser version 4.1.5 ✅  ok
- starting one having jupyterhub single-user server version 3.1.1 ❌  failed

**Comment by GeorgianaElena** [comment]
We will need to get [the changes in the boostrap5 branch into the custom branches](https://github.com/2i2c-org/default-hub-homepage/compare/openscapes...2i2c-org:default-hub-homepage:bootstrap5?expand=1) of https://github.com/2i2c-org/default-hub-homepage that the hubs use (i.e. openscapes)

**Comment by GeorgianaElena** [comment]
Getting the following errors when trying to execute a notebook on the openscapes staging hub

<details>
<summary>error1</summary>

```bash
[W 2024-12-20 18:41:51.143 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 632, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 345, in link_extension
        extension.link_all_points(self.serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 227, in link_all_points
        self.link_point(point_name, serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 217, in link_point
        point.link(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 139, in link
        linker(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 109, in _link_jupyter_server_extension
        members = diff_members(serverapp, nbapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 62, in diff_members
        m1 = public_members(obj1)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 56, in public_members
        members = inspect.getmembers(obj)
      File "/srv/conda/envs/notebook/lib/python3.10/inspect.py", line 469, in getmembers
        value = getattr(object, key)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 687, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 635, in get
        default = obj.trait_defaults(self.name)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 1897, in trait_defaults
        return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/application.py", line 104, in _data_dir_default
        ensure_dir_exists(d, mode=0o700)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 26, in ensure_dir_exists
        Path(path).mkdir(parents=True, mode=mode)
      File "/srv/conda/envs/notebook/lib/python3.10/pathlib.py", line 1175, in mkdir
        self._accessor.mkdir(self, mode)
    PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
[I 2024-12-20 18:41:51.145 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/serverapp.py:2235: JupyterServerAuthWarning: Core endpoints without @allow_unauthenticated, @ws_authenticated, nor @web.authenticated:
- GET of JupyterHubLogoutHandler registered for /user/georgianaelena/logout
- GET of JupyterHubOAuthCallbackHandler registered for /user/georgianaelena/oauth_callback
  self.web_app = ServerWebApplication(
[I 2024-12-20 18:41:51.182 ServerApp] notebook_shim | extension was successfully loaded.
```
</details>

and

<details>
<summary>error2</summary>

```bash
[W 2024-12-20 18:41:51.143 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 632, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 345, in link_extension
        extension.link_all_points(self.serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 227, in link_all_points
        self.link_point(point_name, serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 217, in link_point
        point.link(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 139, in link
        linker(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 109, in _link_jupyter_server_extension
        members = diff_members(serverapp, nbapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 62, in diff_members
        m1 = public_members(obj1)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 56, in public_members
        members = inspect.getmembers(obj)
      File "/srv/conda/envs/notebook/lib/python3.10/inspect.py", line 469, in getmembers
        value = getattr(object, key)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 687, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 635, in get
        default = obj.trait_defaults(self.name)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 1897, in trait_defaults
        return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/application.py", line 104, in _data_dir_default
        ensure_dir_exists(d, mode=0o700)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 26, in ensure_dir_exists
        Path(path).mkdir(parents=True, mode=mode)
      File "/srv/conda/envs/notebook/lib/python3.10/pathlib.py", line 1175, in mkdir
        self._accessor.mkdir(self, mode)
    PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
[I 2024-12-20 18:41:51.145 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/serverapp.py:2235: JupyterServerAuthWarning: Core endpoints without @allow_unauthenticated, @ws_authenticated, nor @web.authenticated:
- GET of JupyterHubLogoutHandler registered for /user/georgianaelena/logout
- GET of JupyterHubOAuthCallbackHandler registered for /user/georgianaelena/oauth_callback
  self.web_app = ServerWebApplication(
[I 2024-12-20 18:41:51.182 ServerApp] notebook_shim | extension was successfully loaded.
```
</details>

**Comment by GeorgianaElena** [comment]
I've updated the top comment with the remaining tests that we should do before considering upgrading.

**Comment by GeorgianaElena** [comment]
>  do one more check with a user image running jupyterhub3. The one I did was on a binderhub

Did another test on earthscope staging with jupyterhub/singleuser:3 that Yuvi suggested and it worked, so there shouldn't be any issues if there are hubs still using JupyterHub 3.

**Comment by GeorgianaElena** [comment]
I believe this was the last thing to test and based on this we can consider upgrading the prod hubs to z2jh 4 safe to try.
