### ISSUE TITLE
[Spike: 1h] openscapes-staging: Investigate why creating and executing notebooks fails with a readonly error

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#5317]
### Context

While testing the z2jh4 upgrade in https://github.com/2i2c-org/infrastructure/issues/5209?, I saw that executing and creating a new notebook on the openscapes staging hub fails with:

<details>
<summary>KeyError: 'data_dir'</summary>

```bash
[W 2024-12-20 18:41:51.143 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 632, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 345, in link_extension
        extension.link_all_points(self.serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 227, in link_all_points
        self.link_point(point_name, serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 217, in link_point
        point.link(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 139, in link
        linker(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 109, in _link_jupyter_server_extension
        members = diff_members(serverapp, nbapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 62, in diff_members
        m1 = public_members(obj1)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 56, in public_members
        members = inspect.getmembers(obj)
      File "/srv/conda/envs/notebook/lib/python3.10/inspect.py", line 469, in getmembers
        value = getattr(object, key)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 687, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 635, in get
        default = obj.trait_defaults(self.name)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 1897, in trait_defaults
        return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/application.py", line 104, in _data_dir_default
        ensure_dir_exists(d, mode=0o700)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 26, in ensure_dir_exists
        Path(path).mkdir(parents=True, mode=mode)
      File "/srv/conda/envs/notebook/lib/python3.10/pathlib.py", line 1175, in mkdir
        self._accessor.mkdir(self, mode)
    PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
[I 2024-12-20 18:41:51.145 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/serverapp.py:2235: JupyterServerAuthWarning: Core endpoints without @allow_unauthenticated, @ws_authenticated, nor @web.authenticated:
- GET of JupyterHubLogoutHandler registered for /user/georgianaelena/logout
- GET of JupyterHubOAuthCallbackHandler registered for /user/georgianaelena/oauth_callback
  self.web_app = ServerWebApplication(
[I 2024-12-20 18:41:51.182 ServerApp] notebook_shim | extension was successfully loaded.
```
</details>

and

<details>
<summary>PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'</summary>

```bash
[W 2024-12-20 18:41:51.143 ServerApp] notebook_shim | error linking extension: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 632, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 345, in link_extension
        extension.link_all_points(self.serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 227, in link_all_points
        self.link_point(point_name, serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 217, in link_point
        point.link(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 139, in link
        linker(serverapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 109, in _link_jupyter_server_extension
        members = diff_members(serverapp, nbapp)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 62, in diff_members
        m1 = public_members(obj1)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/notebook_shim/nbserver.py", line 56, in public_members
        members = inspect.getmembers(obj)
      File "/srv/conda/envs/notebook/lib/python3.10/inspect.py", line 469, in getmembers
        value = getattr(object, key)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 687, in __get__
        return t.cast(G, self.get(obj, cls))  # the G should encode the Optional
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 635, in get
        default = obj.trait_defaults(self.name)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/traitlets/traitlets.py", line 1897, in trait_defaults
        return t.cast(Sentinel, self._get_trait_default_generator(names[0])(self))
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/application.py", line 104, in _data_dir_default
        ensure_dir_exists(d, mode=0o700)
      File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 26, in ensure_dir_exists
        Path(path).mkdir(parents=True, mode=mode)
      File "/srv/conda/envs/notebook/lib/python3.10/pathlib.py", line 1175, in mkdir
        self._accessor.mkdir(self, mode)
    PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter'
[I 2024-12-20 18:41:51.145 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyter_server/serverapp.py:2235: JupyterServerAuthWarning: Core endpoints without @allow_unauthenticated, @ws_authenticated, nor @web.authenticated:
- GET of JupyterHubLogoutHandler registered for /user/georgianaelena/logout
- GET of JupyterHubOAuthCallbackHandler registered for /user/georgianaelena/oauth_callback
  self.web_app = ServerWebApplication(
[I 2024-12-20 18:41:51.182 ServerApp] notebook_shim | extension was successfully loaded.
```
</details>

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/89a12e12-1e29-4713-8283-7aa92fadea2a" />

### Task list

```[tasklist]
 - [ ] .
 - [ ] .
 - [ ] .
```

**Comment by GeorgianaElena** [comment]
I've looked into this more today and realized it was an issue only my username was having. It had to do with some ownership permissions I played with in the past. After deleting my home dir, allowing it to be created with the correct permissions, the issue went away.
